version: '3.4'

services:
  judge-board-srv:
    image: judge-board-srv
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js